version: "3.8"

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn start
    ports:
      - "3070:3000"
