version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    volumes:
      - ./backend:/app
    command: dotnet watch run --urls "http://+:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_CONNECTION_STRING=mysql://user:password@db:3306/todo_db


  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    command: yarn start
    ports:
      - "3070:3000"
  

  db:
    image: mysql:8.0
    platform: linux/amd64
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3030:3306"
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
